name: CreateRelease

on:
  #[push, pull_request] #just for test release scripts
  workflow_dispatch: #manual run
    inputs:
      version:
        description: 'New ReLightLab Version'
        required: true
        default: 'YYYY.MM'

env:
  QT_VERSION: 5.15.2

jobs:
  update_rl_version:
    name: Update RELIGHT_VERSION
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Update ReLight version
      run : |
        echo ${{ github.event.inputs.version }} | tr -d '\n'> RELIGHT_VERSION
    - name: commit RELIGHT_VERSION change
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Set ReLight version to ${{ github.event.inputs.version }}

  relight_build:
    needs: [update_rl_version]
    name: Build ReLightLab
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'macos-latest', 'windows-latest']
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        ref: main
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Set CodeSign Certificate macOS
      if: runner.os == 'macOS'
      uses: apple-actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
        p12-password: ${{ secrets.MACOS_CERTIFICATE_PSSW }}
    - name: Set CodeSign Certificate Windows
      if: runner.os == 'Windows'
      run: |
        New-Item -ItemType directory -Path certificate
        Set-Content -Path certificate\certificate.txt -Value '${{ secrets.WIN_CERTIFICATE }}'
        certutil -decode certificate\certificate.txt certificate\certificate.pfx
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        cache: true
        version: ${{ env.QT_VERSION }}
    - name: Install dependencies
      shell: bash
      run: |
        bash scripts/${{ runner.os }}/0_setup_env.sh --dont_install_qt
    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-${{ github.ref }}
    - name: Configure and Build
      shell: bash
      run: |
        bash scripts/${{ runner.os }}/1_build.sh --ccache --use_brew_llvm
    - name: Deploy
      shell: bash
      run: |
        bash scripts/${{ runner.os }}/2_deploy.sh --cert_pssw='${{ secrets.WIN_CERTIFICATE_PSSW }}' --cert_id='${{ secrets.MACOS_CERT_ID }}' --notarization_user='${{ secrets.MACOS_NOTARIZATION_USER }}' --notarization_team='${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}' --notarization_pssw='${{ secrets.MACOS_NOTARIZATION_PSSW }}'
    - name: Upload ReLightLab Portable
      uses: actions/upload-artifact@v3
      with:
        name: ReLightLab_${{ runner.os }}_portable
        path: install/
    - name: Upload ReLightLab Packages
      uses: actions/upload-artifact@v3
      with:
        name: ReLightLab_${{ runner.os }}_packages
        path: packages/ReLightLab*

  #after building ReLightLab for the three platforms, we create a release in github
  create_release:
    name: Create Release
    needs: [relight_build]
    runs-on: ubuntu-latest
    steps:

    #Download Linux Packages
    - name: Download Linux ZIP
      uses: actions/download-artifact@v3
      with:
        name: ReLightLab_Linux_portable
        path: relighlab_linux_portable
    - name: Download Linux AppImage
      uses: actions/download-artifact@v3
      with:
        name: ReLightLab_Linux_packages
        path: relighlab_linux_appimage
    - name: Change Permissions
      run: |
        chmod +x relighlab_linux_portable/usr/bin/relight
        chmod +x relighlab_linux_portable/usr/bin/relight-cli
        chmod +x relighlab_linux_portable/usr/bin/relight-merge
        chmod +x relighlab_linux_portable/AppRun
    - name: Setup env variables
      id: envs
      shell: bash
      run: |
        #get version of relightlab
        IFS=' ' #space delimiter
        STR_VERSION=$(relightlab_linux_portable/usr/bin/relight --version)
        read -a strarr <<< "$STR_VERSION"
        RL_VERSION=${strarr[1]} #get the relight version from the string
        echo "rl_version=$RL_VERSION" >> $GITHUB_OUTPUT
    - name: Create ReLightLab Portable Linux Archive
      run: |
        cd relighlab_linux_portable
        tar -cvzf ../ReLightLab${{steps.envs.outputs.rl_version}}-linux.tar.gz *
        cd ..

    #Download MacOS Package
    - name: Download MacOS DMG
      uses: actions/download-artifact@v3
      with:
        name: ReLightLab_macOS_packages
        path: relighlab_macos_dmg
    - name: Download MacOS Portable
      uses: actions/download-artifact@v3
      with:
        name: ReLightLab_macOS_portable
        path: relighlab_macos_portable
    - name: Change Permissions
      run: |
        chmod +x relighlab_macos_portable/ReLightLab*.app/Contents/MacOS/relight
        chmod +x relighlab_macos_portable/ReLightLab*.app/Contents/MacOS/relight-cli
        chmod +x relighlab_macos_portable/ReLightLab*.app/Contents/MacOS/relight-merge
    - name: Create ReLightLab Portable MacOS
      run: |
        cd relighlab_macos_portable
        tar -cvzf ../ReLightLab${{steps.envs.outputs.rl_version}}-macos.tar.gz *
        cd ..

    #Download Windows Packages
    - name: Download Windows ZIP
      uses: actions/download-artifact@v3
      with:
        name: ReLightLab_Windows_portable
        path: relighlab_windows_portable
#    - name: Download Windows Installer
#      uses: actions/download-artifact@v3
#      with:
#        name: ReLightLab_Windows_packages
#        path: relighlab_windows_installer
    - name: Create ReLightLab Portable Windows Archive
      run: |
        cd relighlab_windows_portable
        zip -r ../ReLightLab${{steps.envs.outputs.rl_version}}-windows.zip *
        cd ..

    #Create release and upload
    - uses: "marvinpinto/action-automatic-releases@6273874b61ebc8c71f1a61b2d98e234cf389b303"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "ReLightLab-${{steps.envs.outputs.rl_version}}"
        prerelease: false #${{ github.event.inputs.release_candidate }}
        title: "ReLightLab-${{steps.envs.outputs.rl_version}}"
        files: |
          ReLightLab${{steps.envs.outputs.rl_version}}-linux.tar.gz
          relighlab_linux_appimage/ReLightLab${{steps.envs.outputs.rl_version}}-linux.AppImage
          ReLightLab${{steps.envs.outputs.rl_version}}-macos.tar.gz
          relighlab_macos_dmg/ReLightLab${{steps.envs.outputs.rl_version}}-macos.dmg
          ReLightLab${{steps.envs.outputs.rl_version}}-windows.zip
#          relighlab_windows_installer/ReLightLab${{steps.envs.outputs.rl_version}}-windows.exe
