name: Linux

on:
  [push, pull_request]

env:
  QT_VERSION: 5.15.2

jobs:
  linux_build:
    name: Build Relight (Linux)
    runs-on: ubuntu-18.04 #in order to deploy, need to use oldest supported version

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache-${{ env.QT_VERSION }}
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        version: ${{ env.QT_VERSION }}
    - name: Install dependencies
      run: |
        bash build_scripts/${{ runner.os }}/0_setup_env_ubuntu.sh
    - name: Configure and Build
      run: |
        bash build_scripts/${{ runner.os }}/1_build.sh
    - name: Deploy
      run: |
        bash build_scripts/${{ runner.os }}/2_deploy_and_appimage.sh
    - name: Upload Relight Portable
      uses: actions/upload-artifact@v2
      with:
        name: relight_linux_portable
        path: install/
    - name: Upload Relight AppImage
      uses: actions/upload-artifact@v2
      with:
        name: relight_linux_appimage
        path: ReLight*.AppImage
