name: Linux

on:
  [push, pull_request]

jobs:
  linux_build:
    name: Build Relight (Linux)
    runs-on: ubuntu-18.04 #in order to deploy, need to use oldest supported version

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Install dependencies
      run: |
        bash build_scripts/${{ runner.os }}/0_setup_env_ubuntu.sh
    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake -DUSE_QT_5=ON -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX="../install/usr" ..
        make -j4
        make install

    - name: Deploy
      run: |
        mkdir -p install/usr/share/applications/
        mkdir -p install/usr/share/icons/Yaru/512x512/apps/
        cp deploy/linux/relight.desktop install/usr/share/applications/relight.desktop
        cp deploy/linux/relight.png install/usr/share/icons/Yaru/512x512/apps/relight.png
        deploy/linux/linuxdeployqt install/usr/share/applications/relight.desktop -bundle-non-qt-libs -appimage
        rm install/AppRun

    - name: Upload Relight Portable
      uses: actions/upload-artifact@v2
      with:
        name: Relight_linux_portable
        path: install/
    - name: Upload Relight AppImage
      uses: actions/upload-artifact@v2
      with:
        name: Relight_linux_appimage
        path: ReLight*.AppImage
