name: Linux

on:
  [push, pull_request]

jobs:
  linux_build:
    name: Build Relight (Linux)
    runs-on: ubuntu-18.04 #in order to deploy, need to use oldest supported version

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Install dependencies
      run: |
        #apt in 16.04 gets old version of eigen... kept same download for 18.04
        wget http://mirrors.kernel.org/ubuntu/pool/universe/e/eigen3/libeigen3-dev_3.3.4-4_all.deb
        sudo dpkg -i libeigen3-dev*
        sudo apt-get install -y mesa-common-dev libglu1-mesa-dev libjpeg-dev
    - name: Configure and Build
      run: |
        cd relight
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX="../install/usr" ..
        make -j4
        make install
    - name: Deploy
      run: |
        mkdir -p relight/install/usr/share/applications/
        mkdir -p relight/install/usr/share/icons/Yaru/512x512/apps/
        cp deploy/linux/relight.desktop relight/install/usr/share/applications/relight.desktop
        cp deploy/linux/relight.png relight/install/usr/share/icons/Yaru/512x512/apps/relight.png
        deploy/linux/linuxdeployqt relight/install/usr/share/applications/relight.desktop -bundle-non-qt-libs -appimage
    - name: Upload Relight Portable
      uses: actions/upload-artifact@v2
      with:
        name: Relight_linux_portable
        path: relight/install/
    - name: Upload Relight AppImage
      uses: actions/upload-artifact@v2
      with:
        name: Relight_linux_appimage
        path: ReLight*.AppImage
