name: MacOS

on:
  [push, pull_request]

jobs:
  macos_build:
    name: Build Relight (MacOS)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Install dependencies
      run: |
        bash build_scripts/${{ runner.os }}/0_setup_env.sh
    - name: Configure and Build
      run: |

        mkdir build
        cd build
        cmake -DUSE_QT_5=ON -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX="../install" ..
        make -j4
        make install

    - name: Deploy
      run: |
        cd install
        macdeployqt relight.app
    - name: Upload Relight Portable
      uses: actions/upload-artifact@v1
      with:
        name: Relight_macos_portable
        path: install
