name: Windows

on:
  [push, pull_request]

env:
  QT_VERSION: 5.15.2

jobs:
  windows_build:
    name: Build Relight (Windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache-${{ env.QT_VERSION }}
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        version: ${{ env.QT_VERSION }}
    - name: Setup env variables
      shell: bash
      run: |
        echo "VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC" >> $GITHUB_ENV
    - name: Install wget
      run: |
        $env:PATH = "${{ env.PATH }};C:\msys64\mingw64\bin;C:\msys64\usr\bin"
        pacman.exe -S --noconfirm --noprogressbar wget unzip
    - name: Configure and Build
      shell: bash
      run: |
        bash build_scripts/${{ runner.os }}/1_build.sh
    - name: Deploy
      shell: C:\shells\msys2bash.cmd {0}
      run: |
        bash build_scripts/${{ runner.os }}/2_deploy.sh -qt=${{ env.Qt5_DIR }}
    - name: Upload Relight Portable
      uses: actions/upload-artifact@v2
      with:
        name: relight_windows_portable
        path: install
