name: Windows

on: [push, pull_request]

jobs:
  windows_build:
    name: Build Relight (Windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Download Jom
      run: |
        Invoke-WebRequest -Uri "http://mirrors.ukfast.co.uk/sites/qt.io/official_releases/jom/jom_1_1_3.zip" -OutFile "jom_1_1_3.zip"
        New-Item -Name "jom" -ItemType "directory"
        Expand-Archive -Path jom_1_1_3.zip -DestinationPath .\jom
        echo "$(Get-Location)\jom" >> GITHUB_PATH
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Install dependencies
      shell: bash
      run: |
        cd external
        mkdir build
        cd build
        cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
        nmake
        nmake install #dir should be C:\libjpeg-turbo64
        echo "======="
        ls -l C:\libjpeg-turbo64
        echo "======="
    - name: Setup env variables
      shell: bash
      run: |
        echo "JPEGTURBO_HOME=C:\libjpeg-turbo64" >> $GITHUB_ENV
        echo "EIGEN_HOME=$${GITHUB_WORKSPACE}\external\eigen-3.3.9" >> $GITHUB_ENV
    - name: Configure and Build
      shell: bash
      run: |
        cd highlight
        mkdir build
        cd build
        cmake -G "NMake Makefiles" ..
        jom -j4
